// Realistic Indian demo data for Sanvya v2

export const patients = [
  {
    id: "SNV-2024-001",
    name: "Rajesh Kumar Sharma",
    age: 45,
    gender: "Male",
    phone: "+91 98765 43210",
    email: "rajesh.sharma@gmail.com",
    address: "B-12, Vasant Kunj, New Delhi - 110070",
    bloodGroup: "B+",
    admissionDate: "2024-01-15",
    department: "Cardiology",
    ward: "ICU",
    room: "ICU-101",
    bed: "A",
    doctor: "Dr. Anil Kapoor",
    status: "Admitted",
    insurance: "Star Health",
    policyNumber: "SH-2024-789456",
    emergencyContact: "Sunita Sharma - +91 98765 43211",
  },
  {
    id: "SNV-2024-002",
    name: "Priya Patel",
    age: 32,
    gender: "Female",
    phone: "+91 87654 32109",
    email: "priya.patel@yahoo.com",
    address: "404, Satellite Tower, Ahmedabad - 380015",
    bloodGroup: "O+",
    admissionDate: "2024-01-18",
    department: "Gynecology",
    ward: "Maternity",
    room: "MAT-205",
    bed: "B",
    doctor: "Dr. Meera Reddy",
    status: "Admitted",
    insurance: "ICICI Lombard",
    policyNumber: "IL-2024-123789",
    emergencyContact: "Vikram Patel - +91 87654 32108",
  },
  {
    id: "SNV-2024-003",
    name: "Amit Singh",
    age: 58,
    gender: "Male",
    phone: "+91 76543 21098",
    email: "amit.singh@hotmail.com",
    address: "22, Civil Lines, Jaipur - 302006",
    bloodGroup: "A-",
    admissionDate: "2024-01-20",
    department: "Orthopedics",
    ward: "General",
    room: "GEN-312",
    bed: "C",
    doctor: "Dr. Suresh Menon",
    status: "Admitted",
    insurance: "Max Bupa",
    policyNumber: "MB-2024-456123",
    emergencyContact: "Neha Singh - +91 76543 21097",
  },
  {
    id: "SNV-2024-004",
    name: "Lakshmi Venkatesh",
    age: 67,
    gender: "Female",
    phone: "+91 65432 10987",
    email: "lakshmi.v@gmail.com",
    address: "18, T Nagar, Chennai - 600017",
    bloodGroup: "AB+",
    admissionDate: "2024-01-22",
    department: "Neurology",
    ward: "Private AC",
    room: "PVT-401",
    bed: "A",
    doctor: "Dr. Ramesh Iyer",
    status: "Discharged",
    insurance: "Apollo Munich",
    policyNumber: "AM-2024-789012",
    emergencyContact: "Suresh Venkatesh - +91 65432 10986",
  },
  {
    id: "SNV-2024-005",
    name: "Mohammed Farhan",
    age: 28,
    gender: "Male",
    phone: "+91 54321 09876",
    email: "farhan.m@gmail.com",
    address: "56, Banjara Hills, Hyderabad - 500034",
    bloodGroup: "O-",
    admissionDate: "2024-01-25",
    department: "General Medicine",
    ward: "Semi-Private",
    room: "SPV-203",
    bed: "B",
    doctor: "Dr. Kavita Nair",
    status: "Admitted",
    insurance: "Bajaj Allianz",
    policyNumber: "BA-2024-321654",
    emergencyContact: "Ayesha Farhan - +91 54321 09875",
  },
]

export const doctors = [
  {
    id: "DOC-001",
    name: "Dr. Anil Kapoor",
    specialization: "Cardiology",
    department: "Cardiology",
    qualification: "MD, DM (Cardiology), FACC",
    experience: "22 years",
    phone: "+91 99887 76655",
    email: "dr.anil.kapoor@sanvya.com",
    consultationFee: 1500,
    status: "Available",
    rating: 4.8,
    patients: 1250,
    schedule: "Mon-Sat: 9:00 AM - 5:00 PM",
  },
  {
    id: "DOC-002",
    name: "Dr. Meera Reddy",
    specialization: "Gynecology",
    department: "Gynecology",
    qualification: "MS (OBG), DNB",
    experience: "18 years",
    phone: "+91 99776 65544",
    email: "dr.meera.reddy@sanvya.com",
    consultationFee: 1200,
    status: "Available",
    rating: 4.9,
    patients: 980,
    schedule: "Mon-Fri: 10:00 AM - 6:00 PM",
  },
  {
    id: "DOC-003",
    name: "Dr. Suresh Menon",
    specialization: "Orthopedics",
    department: "Orthopedics",
    qualification: "MS (Ortho), MCh",
    experience: "25 years",
    phone: "+91 99665 54433",
    email: "dr.suresh.menon@sanvya.com",
    consultationFee: 1800,
    status: "In Surgery",
    rating: 4.7,
    patients: 1560,
    schedule: "Mon-Sat: 8:00 AM - 4:00 PM",
  },
  {
    id: "DOC-004",
    name: "Dr. Ramesh Iyer",
    specialization: "Neurology",
    department: "Neurology",
    qualification: "MD, DM (Neuro)",
    experience: "20 years",
    phone: "+91 99554 43322",
    email: "dr.ramesh.iyer@sanvya.com",
    consultationFee: 2000,
    status: "Available",
    rating: 4.9,
    patients: 890,
    schedule: "Tue-Sat: 9:00 AM - 5:00 PM",
  },
  {
    id: "DOC-005",
    name: "Dr. Kavita Nair",
    specialization: "General Medicine",
    department: "General Medicine",
    qualification: "MD (Medicine)",
    experience: "15 years",
    phone: "+91 99443 32211",
    email: "dr.kavita.nair@sanvya.com",
    consultationFee: 800,
    status: "On Leave",
    rating: 4.6,
    patients: 2100,
    schedule: "Mon-Fri: 9:00 AM - 6:00 PM",
  },
]

export const departments = [
  { id: "DEP-001", name: "Cardiology", head: "Dr. Anil Kapoor", beds: 45, occupancy: 82, staff: 28 },
  { id: "DEP-002", name: "Gynecology", head: "Dr. Meera Reddy", beds: 35, occupancy: 71, staff: 22 },
  { id: "DEP-003", name: "Orthopedics", head: "Dr. Suresh Menon", beds: 40, occupancy: 65, staff: 25 },
  { id: "DEP-004", name: "Neurology", head: "Dr. Ramesh Iyer", beds: 30, occupancy: 90, staff: 20 },
  { id: "DEP-005", name: "General Medicine", head: "Dr. Kavita Nair", beds: 60, occupancy: 78, staff: 35 },
  { id: "DEP-006", name: "Pediatrics", head: "Dr. Sanjay Gupta", beds: 25, occupancy: 56, staff: 18 },
  { id: "DEP-007", name: "Oncology", head: "Dr. Priya Sharma", beds: 20, occupancy: 85, staff: 15 },
]

export const wards = [
  {
    id: "WRD-001",
    name: "ICU",
    department: "Cardiology",
    category: "AC",
    type: "Intensive Care",
    capacity: 12,
    occupied: 10,
    rate: 15000,
  },
  {
    id: "WRD-002",
    name: "Maternity",
    department: "Gynecology",
    category: "AC",
    type: "Special Care",
    capacity: 20,
    occupied: 14,
    rate: 8000,
  },
  {
    id: "WRD-003",
    name: "General Ward A",
    department: "General Medicine",
    category: "Non-AC",
    type: "General",
    capacity: 30,
    occupied: 24,
    rate: 2500,
  },
  {
    id: "WRD-004",
    name: "Private Ward",
    department: "All",
    category: "AC",
    type: "Private",
    capacity: 15,
    occupied: 12,
    rate: 12000,
  },
  {
    id: "WRD-005",
    name: "Semi-Private",
    department: "All",
    category: "AC",
    type: "Semi-Private",
    capacity: 25,
    occupied: 18,
    rate: 6000,
  },
  {
    id: "WRD-006",
    name: "Pediatric Ward",
    department: "Pediatrics",
    category: "AC",
    type: "Special Care",
    capacity: 15,
    occupied: 8,
    rate: 5000,
  },
  {
    id: "WRD-007",
    name: "Surgical ICU",
    department: "Orthopedics",
    category: "AC",
    type: "Intensive Care",
    capacity: 10,
    occupied: 7,
    rate: 18000,
  },
]

export const rooms = [
  { id: "RM-001", name: "ICU-101", ward: "ICU", category: "AC", beds: 2, occupied: 2, status: "Full" },
  { id: "RM-002", name: "ICU-102", ward: "ICU", category: "AC", beds: 2, occupied: 1, status: "Available" },
  { id: "RM-003", name: "MAT-201", ward: "Maternity", category: "AC", beds: 3, occupied: 2, status: "Available" },
  { id: "RM-004", name: "MAT-202", ward: "Maternity", category: "AC", beds: 3, occupied: 3, status: "Full" },
  {
    id: "RM-005",
    name: "GEN-301",
    ward: "General Ward A",
    category: "Non-AC",
    beds: 6,
    occupied: 5,
    status: "Available",
  },
  { id: "RM-006", name: "PVT-401", ward: "Private Ward", category: "AC", beds: 1, occupied: 1, status: "Full" },
  { id: "RM-007", name: "SPV-201", ward: "Semi-Private", category: "AC", beds: 2, occupied: 1, status: "Available" },
]

export const appointments = [
  {
    id: "APT-001",
    patientId: "SNV-2024-001",
    patientName: "Rajesh Kumar Sharma",
    doctorId: "DOC-001",
    doctorName: "Dr. Anil Kapoor",
    department: "Cardiology",
    date: "2024-01-28",
    time: "10:00 AM",
    type: "Follow-up",
    status: "Confirmed",
  },
  {
    id: "APT-002",
    patientId: "SNV-2024-002",
    patientName: "Priya Patel",
    doctorId: "DOC-002",
    doctorName: "Dr. Meera Reddy",
    department: "Gynecology",
    date: "2024-01-28",
    time: "11:30 AM",
    type: "Consultation",
    status: "Confirmed",
  },
  {
    id: "APT-003",
    patientId: "SNV-2024-003",
    patientName: "Amit Singh",
    doctorId: "DOC-003",
    doctorName: "Dr. Suresh Menon",
    department: "Orthopedics",
    date: "2024-01-28",
    time: "02:00 PM",
    type: "Surgery",
    status: "Pending",
  },
  {
    id: "APT-004",
    patientId: "SNV-2024-005",
    patientName: "Mohammed Farhan",
    doctorId: "DOC-005",
    doctorName: "Dr. Kavita Nair",
    department: "General Medicine",
    date: "2024-01-29",
    time: "09:30 AM",
    type: "Consultation",
    status: "Confirmed",
  },
]

export const labTests = [
  {
    id: "LAB-001",
    patientId: "SNV-2024-001",
    patientName: "Rajesh Kumar Sharma",
    testName: "Complete Blood Count (CBC)",
    category: "Hematology",
    requestedBy: "Dr. Anil Kapoor",
    requestDate: "2024-01-26",
    status: "Completed",
    result: "Normal",
    cost: 450,
  },
  {
    id: "LAB-002",
    patientId: "SNV-2024-001",
    patientName: "Rajesh Kumar Sharma",
    testName: "Lipid Profile",
    category: "Biochemistry",
    requestedBy: "Dr. Anil Kapoor",
    requestDate: "2024-01-26",
    status: "Completed",
    result: "Elevated LDL",
    cost: 750,
  },
  {
    id: "LAB-003",
    patientId: "SNV-2024-002",
    patientName: "Priya Patel",
    testName: "Thyroid Profile",
    category: "Hormone",
    requestedBy: "Dr. Meera Reddy",
    requestDate: "2024-01-27",
    status: "In Progress",
    result: "Pending",
    cost: 850,
  },
  {
    id: "LAB-004",
    patientId: "SNV-2024-003",
    patientName: "Amit Singh",
    testName: "X-Ray (Knee)",
    category: "Radiology",
    requestedBy: "Dr. Suresh Menon",
    requestDate: "2024-01-25",
    status: "Completed",
    result: "Osteoarthritis Grade II",
    cost: 600,
  },
]

export const billing = [
  {
    id: "BIL-001",
    patientId: "SNV-2024-001",
    patientName: "Rajesh Kumar Sharma",
    roomCharges: 45000,
    doctorFees: 4500,
    nursingCharges: 6000,
    labCharges: 1200,
    medicineCharges: 8500,
    surgeryCharges: 0,
    miscCharges: 2000,
    totalAmount: 67200,
    insuranceCovered: 50000,
    patientPayable: 17200,
    status: "Pending",
  },
  {
    id: "BIL-002",
    patientId: "SNV-2024-002",
    patientName: "Priya Patel",
    roomCharges: 24000,
    doctorFees: 3600,
    nursingCharges: 4000,
    labCharges: 850,
    medicineCharges: 5200,
    surgeryCharges: 0,
    miscCharges: 1500,
    totalAmount: 39150,
    insuranceCovered: 30000,
    patientPayable: 9150,
    status: "Partial",
  },
  {
    id: "BIL-003",
    patientId: "SNV-2024-004",
    patientName: "Lakshmi Venkatesh",
    roomCharges: 48000,
    doctorFees: 6000,
    nursingCharges: 8000,
    labCharges: 2500,
    medicineCharges: 12000,
    surgeryCharges: 0,
    miscCharges: 3000,
    totalAmount: 79500,
    insuranceCovered: 60000,
    patientPayable: 19500,
    status: "Paid",
  },
]

export const surgeries = [
  {
    id: "SRG-001",
    patientId: "SNV-2024-003",
    patientName: "Amit Singh",
    surgeryName: "Total Knee Replacement",
    surgeon: "Dr. Suresh Menon",
    anesthetist: "Dr. Vikram Joshi",
    scheduledDate: "2024-01-30",
    scheduledTime: "09:00 AM",
    operationTheatre: "OT-2",
    estimatedDuration: "3 hours",
    status: "Scheduled",
    preOpNotes: "Patient cleared for surgery. NPO from midnight.",
  },
  {
    id: "SRG-002",
    patientId: "SNV-2024-001",
    patientName: "Rajesh Kumar Sharma",
    surgeryName: "Coronary Angioplasty",
    surgeon: "Dr. Anil Kapoor",
    anesthetist: "Dr. Neeta Sharma",
    scheduledDate: "2024-02-05",
    scheduledTime: "08:00 AM",
    operationTheatre: "Cath Lab",
    estimatedDuration: "2 hours",
    status: "Scheduled",
    preOpNotes: "Contrast allergy test negative. Blood arranged.",
  },
]

export const notifications = [
  {
    id: 1,
    title: "New Admission",
    message: "Patient Rajesh Kumar Sharma admitted to ICU",
    time: "10 mins ago",
    type: "admission",
  },
  { id: 2, title: "Lab Report Ready", message: "CBC report ready for Priya Patel", time: "25 mins ago", type: "lab" },
  {
    id: 3,
    title: "Appointment Reminder",
    message: "Dr. Anil Kapoor has 3 appointments today",
    time: "1 hour ago",
    type: "appointment",
  },
  {
    id: 4,
    title: "Surgery Scheduled",
    message: "Knee replacement surgery scheduled for Amit Singh",
    time: "2 hours ago",
    type: "surgery",
  },
  {
    id: 5,
    title: "Payment Received",
    message: "₹19,500 payment received from Lakshmi Venkatesh",
    time: "3 hours ago",
    type: "billing",
  },
]

export const analyticsData = {
  totalPatients: 1250,
  admittedPatients: 145,
  todayAppointments: 48,
  pendingBills: 32,
  totalRevenue: 4520000,
  monthlyGrowth: 12.5,
  bedOccupancy: 76,
  avgStayDuration: 4.2,
}
